### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by derek-watson** [dominictarr/reconnect#19]
Hello,

I'm unable to install `lev`, the leveldb cli because it depends on `reconnect`, which fails to install due to the following failing dependencies.

What is going on here and how do we fix it?

```
$ npm install reconnect
...
npm http 304 https://registry.npmjs.org/engine.io-client
npm ERR! git fetch -a origin (git://github.com/substack/sockjs-client.git) error: cannot open FETCH_HEAD: Permission denied
npm WARN optional dep failed, continuing sockjs-stream@0.1.3
npm ERR! git fetch -a origin (git://github.com/shtylman/engine.io-client) error: cannot open FETCH_HEAD: Permission denied
npm ERR! Error: No compatible version found: engine.io-client@'shtylman/engine.io-client#v0.5.0-dz0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.6","0.3.7","0.3.8","0.3.9","0.3.10","0.4.0","0.4.1","0.4.2","0.4.3","0.5.0","0.6.0","0.6.1","0.6.2","0.6.3","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","0.7.6","0.7.7","0.7.8","0.7.9","0.7.10","0.7.11","0.7.12"]
npm ERR!     at installTargetsError (/Users/watson/.nvm/v0.10.20/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /Users/watson/.nvm/v0.10.20/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/Users/watson/.nvm/v0.10.20/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /Users/watson/.nvm/v0.10.20/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/Users/watson/.nvm/v0.10.20/bin/node" "/Users/watson/.nvm/v0.10.20/bin/npm" "install" "reconnect"
npm ERR! cwd /Users/watson/Projects/lev
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/watson/Projects/lev/npm-debug.log
npm ERR! not ok code 0
```

**Comment by dominictarr** [comment]
hmm. I don't really use that version:

@hij1nx @raynos @defuctzombie which version works?

I will republish at 0.7, so that at least it installs.

**Comment by dominictarr** [comment]
oh, hang on... reconnect installed for me just fine...
maybe it's just lev?

**Comment by dominictarr** [comment]
it's installing engine.io-client from github, maybe github was down when you ran install?

**Comment by derek-watson** [comment]
I guess I'm an npm newbie, it was this https://github.com/isaacs/npm/issues/3350.

Thanks for your help Dominic!

**Comment by dominictarr** [comment]
no problem!

**Comment by KyleAMathews** [comment]
I found this issue while trying to install lev as well. I get a similar but slightly different error either when I try to install lev or reconnect directly. Setting permissions on ~/.npm didn't help. Any idea what's going on?

```
make: Leaving directory `/usr/local/lib/node_modules/reconnect/node_modules/sockjs-stream/node_modules/ws/build'
npm http GET https://registry.npmjs.org/engine.io/0.4.3
npm http GET https://registry.npmjs.org/engine.io-client
npm http 304 https://registry.npmjs.org/engine.io/0.4.3
npm http 304 https://registry.npmjs.org/engine.io-client
npm ERR! Error: No compatible version found: engine.io-client@'shtylman/engine.io-client#v0.5.0-dz0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.6","0.3.7","0.3.8","0.3.9","0.3.10","0.4.0","0.4.1","0.4.2","0.4.3","0.5.0","0.6.0","0.6.1","0.6.2","0.6.3","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","0.7.6","0.7.7","0.7.8","0.7.9","0.7.10","0.7.11","0.7.12"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:553:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:477:15
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:220:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.9.9-302.fc19.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "reconnect"
npm ERR! cwd /opt/desk.com
npm ERR! node -v v0.8.9
npm ERR! npm -v 1.1.61
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/desk.com/npm-debug.log
npm ERR! not ok code 0
```

**Comment by dominictarr** [comment]
this is going to be fixed soon, as described here: https://github.com/dominictarr/reconnect/issues/20#issuecomment-29455902

**Comment by dominictarr** [comment]
okay, so the problem here is that shtylman has changed his name to defunctzombie
_that_ coupled with the fact that github defaults to download by .zip, but since the tools to unpack tar are better, I found a way to get github to give me a tar...
BUT github don't do redirects for that...
so this actually causes github to 500...

**Comment by dominictarr** [comment]
I shall put in a support email.

**Comment by KyleAMathews** [comment]
Was this fixed?

**Comment by dominictarr** [comment]
ah, that problem was solved, but it's still not working. I will start working on this stuff again soon,
and I'll use installing this module as a test case.
