### ISSUE TITLE
reconnect/sockjs

### ISSUE THREAD

**Issue by Raynos** [dominictarr/reconnect#4]
reconnect/shoe is pretty cool but can't be used on the server.

I'll make a pull request that adds sockjs.js for doing reconnect on the server with sockJS

**Comment by refset** [comment]
Is there an example of this working? I have tried modifying example/shoe/client.js to use `require('../../shoe')` and removed the dom noise but I get this error on the server when I try to connect the client:

```
/home/jeremy/reconnect/examples/shoe/server.js:14
    console.log(stream._session.recv.ws.request)
                                       ^
TypeError: Cannot read property 'request' of undefined
    at /home/jeremy/reconnect/examples/shoe/server.js:14:40
    at Server.handler (/home/jeremy/reconnect/node_modules/shoe/index.js:22:9)
    at Server.EventEmitter.emit (events.js:95:17)
    at App.emit (/home/jeremy/reconnect/node_modules/shoe/node_modules/sockjs/lib/sockjs.js:182:27)
    at new RawWebsocketSessionReceiver (/home/jeremy/reconnect/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:155:14)
    at ws.onopen (/home/jeremy/reconnect/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:52:16)
    at EventTarget.dispatchEvent (/home/jeremy/reconnect/node_modules/shoe/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:36:30)
    at API._open (/home/jeremy/reconnect/node_modules/shoe/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:22:10)
    at /home/jeremy/reconnect/node_modules/shoe/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket.js:50:38
    at process._tickCallback (node.js:415:13)
```

I'd be happy to build it out into a failing example that we can merge once fixed!

**Comment by Raynos** [comment]
@jez0990 I always use `reconnect/inject` manually. I use it with `shoe` or `engine.io`. People also say good things about `engine.io-stream`

**Comment by dominictarr** [comment]
@jez0990 a failing example would be great! will merge!

**Comment by refset** [comment]
@Raynos thanks for the pointers, I will check them out :)

@dominictarr here's the example:
https://github.com/jez0990/reconnect/commit/d76f15f0ad8fd9034aa4c48fce632047873c6d5e

Simply do `npm start` and separately `node node-client.js`

(your original client.js needs updating to use `../../shoe` as well)

Cheers!

**Comment by refset** [comment]
@Raynos is the engine.io-stream supposed to be able to connect to a shoe server? I'm having no luck :(

I also tried using websocket-stream...

Any pointers on how I might fix this issue though? I really want to figure this out.

**Comment by Raynos** [comment]
@jez0990 it has to connect to an engine.io server.

**Comment by dominictarr** [comment]
@jez0990 the only problem was in a `console.log` if you commented that line it worked.
I've fixed it now. 0e04c527a26a5cfdf97072568a804c99c21ac8dd

**Comment by refset** [comment]
Thanks!! Very much appreciated. I did eventually discover that the `console.log` itself was _a_ culprit but didn't know if the implications were wider.
